Styling
irisSchaffer/enorett pull request #1
Opened 2018-05-03 15:28 UTC by IanHazelton

Perhaps a pull-request is a good idea for this first one.

2018-05-06 15:44 UTC, irisSchaffer requested changes

2018-05-06 15:44 UTC, irisSchaffer commented on src/scss/test.scss
> +body {
could we rename this file? Only had it in there as a test :)

2018-05-08 17:00 UTC, IanHazelton commented on src/scss/test.scss
> +body {
Of course. Otherwise, it looks ok?

2018-05-17 11:56 UTC, irisSchaffer commented on src/scss/_colours.scss
> +body {
this should probably not live within `_colours`, I guess? :)

2018-05-25 16:17 UTC, irisSchaffer approved these changes

2018-05-25 20:19 UTC, merged